//
// Generated file, do not edit! Created by nedtool 5.5 from builder/control.msg.
//

#ifndef __CONTROL_M_H
#define __CONTROL_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class Control;
/**
 * Class generated from <tt>builder/control.msg:16</tt> by nedtool.
 * <pre>
 * message Control
 * {
 *     string command;
 * }
 * </pre>
 */
class Control : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string command;

  private:
    void copy(const Control& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Control&);

  public:
    Control(const char *name=nullptr, short kind=0);
    Control(const Control& other);
    virtual ~Control();
    Control& operator=(const Control& other);
    virtual Control *dup() const override {return new Control(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getCommand() const;
    virtual void setCommand(const char * command);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Control& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Control& obj) {obj.parsimUnpack(b);}

#endif // ifndef __CONTROL_M_H

